controller_manager:
  ros__parameters:
    update_rate: 1000 # update rate in Hz

    use_sim_time: true

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

#position controller
position_controller:
  ros__parameters:
    joints:
      - robot_base
      - vertical_rail
      - prismatic_base
      - prismatic_arm
      - gripper_base
      - robotiq_85_right_knuckle_joint
      - robotiq_85_left_knuckle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
